Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [32]:
import numpy as np

In [39]:
def create_array(n):
    
    for i in range(0,n):
        x = np.arange(0,n)
        
    print(x[::-1])

In [41]:
create_array(7)

[6 5 4 3 2 1 0]


Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [43]:
Z = np.diag(np.arange(1, 5))
print(Z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [69]:
def create_diag_array(n):
    
    x = np.diag(np.arange(1, n))
    print(x) 
    
    diag_sum=0
    for i in range (0,n-1):
        diag_sum += x[i][i]
        
    print(diag_sum)

In [71]:
create_diag_array(5)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
10


Задание 3

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [135]:
import pandas as pd

In [136]:
movies = pd.read_csv('movies.csv')
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [163]:
ratings = pd.read_csv('ratings.csv')
ratings.head()

userId  movieId  rating     timestamp
0       1      2.0     3.5  1.112486e+09
1       1     29.0     3.5  1.112485e+09
2       1     32.0     3.5  1.112485e+09
3       1     47.0     3.5  1.112485e+09
4       1     50.0     3.5  1.112485e+09

In [166]:
ratings_5 = ratings[ ratings['rating'] == 5.0 ]
ratings_5.head()

userId  movieId  rating     timestamp
131       1   4993.0     5.0  1.112485e+09
142       1   5952.0     5.0  1.112485e+09
158       1   7153.0     5.0  1.112485e+09
170       1   8507.0     5.0  1.094786e+09
176       2     62.0     5.0  9.748206e+08

In [168]:
ratings_5['movieId'].value_counts().head()

318.0    8234
296.0    6959
593.0    5733
527.0    5718
260.0    5630
Name: movieId, dtype: int64

In [169]:
best_movie = movies[ movies['movieId'] == 318 ]
best_movie

movieId                             title       genres
315      318  Shawshank Redemption, The (1994)  Crime|Drama

Задание 4

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [177]:
data = pd.read_csv('power.csv')
data.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [182]:
data_sorted = data [ ( (data['country'] == 'Latvia') | (data['country'] == 'Lithuania') | (data['country'] == 'Estonia') )
& (data['year'] >= 2005) & (data['year'] <= 2010) & (data['quantity'] > 0)
& ((data['category'] == 4) | (data['category'] == 12) | (data['category'] == 21))  ]

In [183]:
data_sorted.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4

In [186]:
data_sorted[['country', 'quantity']].groupby(['country']).sum()

quantity
country            
Estonia     63440.0
Latvia      54844.0
Lithuania  122296.0

Задание 5

In [190]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [191]:
from numpy import linalg

In [192]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [193]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True